### ISSUE TITLE
Cognitive Search UI Template error

### ISSUE THREAD

**Issue by stgiesbrecht** [Azure-Samples/azure-search-knowledge-mining#75] opened 2020-12-10 22:58 UTC
### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Generated the Azure services in previous modules
Updated the appsettings.json
Ran the program and as soon as the web page load and I type a search value in the search field and press enter, the program stops with the following error
### Any log messages given by the failure
>'Exception User-Unhandled' - System.UriFormatException: 'Invalid URI: The URI is empty' on line 413 in file DocumentSearchClient.cs where it is trying to create a new BlobContainerClient

### Expected/desired behavior
>

### OS and Version?
> Windows 10
### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by dereklegenzoff** [comment] 2020-12-11 00:25
Hi @stgiesbrecht - issues like this are typically caused by an issue in appsettings.json. Could you confirm you've updated the `StorageContainerAddress` setting and that it's in the following format?

```
"StorageContainerAddress": "https://{storage-account-name}.blob.core.windows.net/{container-name}"
```

**Comment by stgiesbrecht** [comment] 2020-12-11 14:47
Yes, it is the right format. If I set bolded variable below directly to the string that I have in StorageContainerAddress then the program runs. The other app settings are being passed through 

BlobContainerClient container = new BlobContainerClient(new Uri(**s_containerAddresses[i]**), new StorageSharedKeyCredential(accountName, accountKey));

![image](https://user-images.githubusercontent.com/75814811/101917101-79832f00-3b8d-11eb-9af0-25c89f2f40e0.png)

**Comment by stgiesbrecht** [comment] 2020-12-11 14:58
Did some more testing and it appears if I leave StorageContainerAddress2 and 3 as "" then the error occurs. If I put the same string as StorageContainerAddress1 in all three then it runs

**Comment by stgiesbrecht** [comment] 2020-12-11 19:51
I found the issue, I was deleting out the default values form 2 and 3 rather than just leaving it there. It now runs but the results page comes up with 0 results no matter what I enter. If I click on the 'View Entity Map' and choose a facet an entity map appears and can query other stuff. I have used 'Search explorer' from the Azure Portal and confirmed that there are results returned for the values that I am trying on the compiled search page. Any thoughts. I have cloned the GitHub repository, followed the steps to deploy the Azure resources, upload the sample data and create the index.

**Comment by dereklegenzoff** [comment] 2020-12-14 15:57
I'm glad you got the first issue figured out. How did you go about creating the search index? I'm wondering if one of the fields configured incorrectly. Could you right click on the web page -> inspect -> and see if there are any errors in the console? ([link](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console#:~:text=To%20open%20the%20Console%20tool%20in%20Microsoft%20Edge%2C,running%20webpage.%20You%20can%20use%20the%20Console%20to%3A) for more details). That will help us figure out what is going on.

**Comment by stgiesbrecht** [comment] 2020-12-14 16:12
I created the search index as specified in the tutorial. When I run solution I get the following error on the start page
![image](https://user-images.githubusercontent.com/75814811/102104589-fa436480-3df3-11eb-96b6-dc14f8bae8f7.png)

This the error if I type 'microsoft' and click on the magnifying glass
![image](https://user-images.githubusercontent.com/75814811/102104995-72118f00-3df4-11eb-9372-e7b9376b0c8f.png)

And when I click on the 'Entity map' and display facet 'People', I see results but the page has these
![image](https://user-images.githubusercontent.com/75814811/102105244-cae12780-3df4-11eb-9f8d-2936f6531f89.png)

**Comment by dereklegenzoff** [comment] 2020-12-14 23:13
hmm, that is quite odd. It looks like `data.results` is not populated in **results.js** for some reason--that's the object that holds all of the search results. That's not the error I was expecting. 

If you're able to, try putting a breakpoint on line 101 of **DocumentSearchClient.cs** to try to see if any errors happen in the search function

```csharp
            catch (Exception ex)
            {
                Console.WriteLine("Error querying index: {0}\r\n", ex.Message.ToString());
            }
```

It might also be worth trying to create the index again in the portal and make sure everything matches. Or you could try to create the index using the postman collection. 

You can also send me a quick note at derek.legenzoff@microsoft.com and we can set up some time to debug together.

**Comment by stgiesbrecht** [comment] 2020-12-15 16:54
Ok, I deleted the indexer, index and skillset and created them all again. I then pulled all the code again and updated my VS2019 and built the solution again and all is good. Appreciate the help and suggestions.

One question I have is that in the appsettings if I set the SearchApiKey to the 'Query Key', I get the following
![image](https://user-images.githubusercontent.com/75814811/102245838-a43df200-3ec3-11eb-8c5b-1480185f24b6.png)

If I use either of the admin keys then everything works. Is there something that I am missing?

**Comment by dereklegenzoff** [comment] 2020-12-15 17:00
You're very welcome! The way the UI is designed it requires the admin key because it does a few other things such as pulling back the schema of the index to help simplify the experience.

**Comment by stgiesbrecht** [comment] 2020-12-15 17:42
Sounds good, I wasn't sure if I had things setup correctly as the instructions were not clear on which search key to use. Thanks again for everything.

**Comment by dereklegenzoff** [comment] 2020-12-15 17:44
Thank you. I'll have to make an update to call out that the admin key is required. I'll close this issue for now -- please feel free to reopen it if you face any additional issues.

**Closed by dereklegenzoff** 2020-12-15 17:44 UTC
